spring:
    application:
        name: pricing-service
    datasource:
        url: jdbc:h2:file:~/h2/pricing_db;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        generate-ddl: false
        hibernate.ddl-auto: validate
        properties.hibernate.dialect: org.hibernate.dialect.H2Dialect


ribbon:
    http:
        client:
            enabled: true

app:
    services:
        - title: products
          hostName: product-catalog-service
          path: /products

#flyway:
#     enabled: false
#    schemas: pricing_db
#    baselineOnMigrate: true