spring:
    application:
        name: product-catalog-service
    datasource:
        url: jdbc:h2:file:~/h2/product_catalog_db;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        generate-ddl: false
        hibernate.ddl-auto: validate
        properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

#flyway:
#     enabled: false
#    schemas: product_catalog_db
#    baselineOnMigrate: true